// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABFMApbRXyw4jBQzP1JDvL4Q0i7cXLBy4',
    appId: '1:403105079272:web:996858ec6170db7552ce5d',
    messagingSenderId: '403105079272',
    projectId: 'blog-application-f9e6a',
    authDomain: 'blog-application-f9e6a.firebaseapp.com',
    storageBucket: 'blog-application-f9e6a.appspot.com',
    measurementId: 'G-81CK9CMEKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcHMxgNj-obDjVyWYJVjbX3c5VWJp1Fzo',
    appId: '1:403105079272:android:7017dae4771280d452ce5d',
    messagingSenderId: '403105079272',
    projectId: 'blog-application-f9e6a',
    storageBucket: 'blog-application-f9e6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-XYOTVCOgdSpW0auL80SDkixOJypKXXA',
    appId: '1:403105079272:ios:096d0e79d438e93152ce5d',
    messagingSenderId: '403105079272',
    projectId: 'blog-application-f9e6a',
    storageBucket: 'blog-application-f9e6a.appspot.com',
    iosBundleId: 'com.example.blogApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-XYOTVCOgdSpW0auL80SDkixOJypKXXA',
    appId: '1:403105079272:ios:096d0e79d438e93152ce5d',
    messagingSenderId: '403105079272',
    projectId: 'blog-application-f9e6a',
    storageBucket: 'blog-application-f9e6a.appspot.com',
    iosBundleId: 'com.example.blogApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABFMApbRXyw4jBQzP1JDvL4Q0i7cXLBy4',
    appId: '1:403105079272:web:402c8fa1b585d80252ce5d',
    messagingSenderId: '403105079272',
    projectId: 'blog-application-f9e6a',
    authDomain: 'blog-application-f9e6a.firebaseapp.com',
    storageBucket: 'blog-application-f9e6a.appspot.com',
    measurementId: 'G-GMHEZ5LNFF',
  );

}