// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpUNDebJy5kyFKqAUQMSav64OU46L48tQ',
    appId: '1:258006376799:web:4947f7db3700d8290416ea',
    messagingSenderId: '258006376799',
    projectId: 'blogapplication-80ede',
    authDomain: 'blogapplication-80ede.firebaseapp.com',
    storageBucket: 'blogapplication-80ede.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMOyV75HlYMHyBOaWqy1v12RafreATHSs',
    appId: '1:258006376799:android:97f8f7c02dc026e90416ea',
    messagingSenderId: '258006376799',
    projectId: 'blogapplication-80ede',
    storageBucket: 'blogapplication-80ede.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVGUmJg6t4h3ZkDNmM_Px8USuPUzgDTns',
    appId: '1:258006376799:ios:4532f661e494ffc80416ea',
    messagingSenderId: '258006376799',
    projectId: 'blogapplication-80ede',
    storageBucket: 'blogapplication-80ede.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVGUmJg6t4h3ZkDNmM_Px8USuPUzgDTns',
    appId: '1:258006376799:ios:4532f661e494ffc80416ea',
    messagingSenderId: '258006376799',
    projectId: 'blogapplication-80ede',
    storageBucket: 'blogapplication-80ede.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpUNDebJy5kyFKqAUQMSav64OU46L48tQ',
    appId: '1:258006376799:web:097c52ce2ceed1500416ea',
    messagingSenderId: '258006376799',
    projectId: 'blogapplication-80ede',
    authDomain: 'blogapplication-80ede.firebaseapp.com',
    storageBucket: 'blogapplication-80ede.appspot.com',
  );

}